### PR TITLE
 Fetch queue name from ActiveJob class

### LINKED ISSUE #437: [ActiveJob] Cannot use `queue_as` for select queue, only sidekiq options are supported (first run)
Hi :wave: 

looks like sidekiq-cron works "okayish" with ActiveJob. It detects and runs jobs:)

There are 2 problems I'm running into

1. [here](https://github.com/sidekiq-cron/sidekiq-cron/blob/78eb493adbfeb908861ec9b3a76e5e7a01adf339/lib/sidekiq/cron/job.rb#L322) only sidekiq options are fetched on init, if sidekiq options change later on, this will not be fetched
2. When some of the options change, for example queue, it will be **only** overwritten if passed by args [see here](https://github.com/sidekiq-cron/sidekiq-cron/blob/78eb493adbfeb908861ec9b3a76e5e7a01adf339/lib/sidekiq/cron/job.rb#L334).

No code here supports ActiveJob configuration.

Is this more of a bug and PRs to get better ActiveJob is welcome or there's something wrong I'm doing?

Repro is very minimal

```yml
  foobar:
    cron: "*/5 * * * *" 
    class: "FooBar"
```

```rb
  class FooBar < ApplicationJob
    queue_as :low

    def perform
```

### PR DESCRIPTION
**Pull request by arathunku**
ActiveJob queue_as configuration is now used to update Job's queue, previously only Sidekiq::Worker jobs class options were fetched.

As in case with Sidekiq::Workers, queue option in config always takes precedence over queue_as in ActiveJob class.

Fixes #437

### CODE REVIEW

File: test/unit/job_test.rb [hunk 1]
```diff
@@ -643,7 +655,7 @@
 
         describe 'with non sidekiq job class' do
           before do
-            @job = Sidekiq::Cron::Job.new(@args.merge(klass: 'CronTestClass'))
+            @job = Sidekiq::Cron::Job.new(@args.merge(klass: 'ActiveJobCronTestClass'))
```
Comment (arathunku) [inline test/unit/job_test.rb:658]: This is not clearly visible on diff, but this is in `active_job == true` block thus I'd say it's safe to assume any klass at least mimics ActiveJob interface. This may be a breaking change if someone's using  'active_job == true` in config with non-ActiveJob class because `queue_name` on class might not be available :cry:

**Review by markets — APPROVED** [review]
Thanks @arathunku!

**Comment by arathunku** [comment]
Woa, that was fast @markets! Thank you!!!
